enabled = true

[db_multi_connection_logger]
enable = false

[execution_time_logger]
enable = true
interceptions = [ "DefaultRequestCoordinator", "SessionDataStore", "AbstractUserStoreManager", "AccessTokenIssuer", "AccessTokenDAOImpl", "RequestObjectDAOImpl", "AuthorizationCodeDAOImpl", "OAuthScopeDAOImpl", "ReceiptDAOImpl", "PurposeDAOImpl", "PurposeCategoryDAOImpl", "PIICategoryDAOImpl","DefaultStepBasedSequenceHandler","GraphBasedSequenceHandler","JDBCPersistenceManager","UmPersistenceManager"]

# Comment out unwanted interceptions.
[[interception]]
name="data_source_proxy"
class="org.apache.tomcat.jdbc.pool.DataSourceProxy"

[[data_source_proxy]]
method = "getConnection"
arguments = []					# Empty for 0 argument and class name for other types
return = "java.sql.Connection"			# Empty for void and class name for other types.

[[interception]]
name="DefaultRequestCoordinator"
class="org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.DefaultRequestCoordinator"
all_public_methods = true

[[interception]]
name="AbstractUserStoreManager"
class="org.wso2.carbon.user.core.common.AbstractUserStoreManager"
all_public_methods = true

[[interception]]
name="AccessTokenIssuer"
class="org.wso2.carbon.identity.oauth2.token.AccessTokenIssuer"

[[AccessTokenIssuer]]
method = "issue"
arguments = ["org.wso2.carbon.identity.oauth2.dto.OAuth2AccessTokenReqDTO"]
return = "org.wso2.carbon.identity.oauth2.dto.OAuth2AccessTokenRespDTO"

[[interception]]
name="SessionDataStore"
class="org.wso2.carbon.identity.application.authentication.framework.store.SessionDataStore"
all_public_methods = true

[[interception]]
name="AccessTokenDAOImpl"
class="org.wso2.carbon.identity.oauth2.dao.AccessTokenDAOImpl"
all_public_methods = true

[[interception]]
name="RequestObjectDAOImpl"
class="org.wso2.carbon.identity.openidconnect.dao.RequestObjectDAOImpl"
all_public_methods = true


[[interception]]
name="AuthorizationCodeDAOImpl"
class="org.wso2.carbon.identity.oauth2.dao.AuthorizationCodeDAOImpl"
all_public_methods = true

[[interception]]
name="OAuthScopeDAOImpl"
class="org.wso2.carbon.identity.oauth2.dao.OAuthScopeDAOImpl"
all_public_methods = true

[[interception]]
name="ReceiptDAOImpl"
class="org.wso2.carbon.consent.mgt.core.dao.impl.ReceiptDAOImpl"
all_public_methods = true

[[interception]]
name="PurposeDAOImpl"
class="org.wso2.carbon.consent.mgt.core.dao.impl.PurposeDAOImpl"
all_public_methods = true

[[interception]]
name="PurposeCategoryDAOImpl"
class="org.wso2.carbon.consent.mgt.core.dao.impl.PurposeCategoryDAOImpl"
all_public_methods = true

[[interception]]
name="PIICategoryDAOImpl"
class="org.wso2.carbon.consent.mgt.core.dao.impl.PIICategoryDAOImpl"
all_public_methods = true

[[interception]]
name="DefaultStepBasedSequenceHandler"
class="org.wso2.carbon.identity.application.authentication.framework.handler.sequence.impl.DefaultStepBasedSequenceHandler"
all_public_methods = true

[[interception]]
name="GraphBasedSequenceHandler"
class="org.wso2.carbon.identity.application.authentication.framework.handler.sequence.impl.GraphBasedSequenceHandler"
all_public_methods = true

[[interception]]
name="JDBCPersistenceManager"
class="org.wso2.carbon.identity.core.persistence.JDBCPersistenceManager"
all_public_methods = true

[[interception]]
name="UmPersistenceManager"
class="org.wso2.carbon.identity.core.persistence.UmPersistenceManager"
all_public_methods = true
